<?php

namespace Tests\Feature\Superadmin;

use App\Models\Business;
use App\Models\Role;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Hash;
use Tests\TestCase;

class SuperadminBusinessUserTest extends TestCase
{
    use RefreshDatabase;

    protected User $superadmin;
    protected User $normalUser;
    protected Business $business;
    protected Role $adminRole;
    protected Role $employeeRole;

    protected function setUp(): void
    {
        parent::setUp();

        $this->adminRole = Role::create([
            'name' => 'Administrador',
            'slug' => Role::ROLE_ADMIN,
        ]);

        $this->employeeRole = Role::create([
            'name' => 'Empleado',
            'slug' => Role::ROLE_EMPLOYEE,
        ]);

        $this->superadmin = User::factory()->create([
            'is_superadmin' => true,
            'must_change_password' => false,
        ]);

        $this->normalUser = User::factory()->create([
            'is_superadmin' => false,
            'must_change_password' => false,
        ]);

        $this->business = Business::create([
            'name' => 'Restaurante Cali Mío',
            'business_type' => 'restaurant',
            'status' => 'active',
            'is_active' => true,
        ]);
    }

    public function test_superadmin_can_view_users_create_form(): void
    {
        $response = $this->actingAs($this->superadmin)
            ->get(route('superadmin.businesses.users.create', $this->business));

        $response->assertOk();
        $response->assertSee('Agregar Colaborador');
        $response->assertSee('Restaurante Cali Mío');
        $response->assertSee('Administrador');
        $response->assertSee('Empleado');
    }

    public function test_superadmin_can_create_admin_user_for_business(): void
    {
        $response = $this->actingAs($this->superadmin)
            ->post(route('superadmin.businesses.users.store', $this->business), [
                'name' => 'Carlos Administrador',
                'email' => 'carlos.admin@puntostock.co',
                'role' => 'admin',
                'password' => 'Temporal123!',
            ]);

        $response->assertRedirect(route('superadmin.businesses.users', $this->business));
        $response->assertSessionHas('temp_password', 'Temporal123!');
        $response->assertSessionHas('created_user_email', 'carlos.admin@puntostock.co');

        $newUser = User::where('email', 'carlos.admin@puntostock.co')->first();
        $this->assertNotNull($newUser);
        $this->assertEquals('Carlos Administrador', $newUser->name);
        $this->assertTrue((bool) $newUser->must_change_password);
        $this->assertFalse((bool) $newUser->is_superadmin);
        $this->assertTrue(Hash::check('Temporal123!', $newUser->password));

        $this->assertDatabaseHas('business_user', [
            'business_id' => $this->business->id,
            'user_id' => $newUser->id,
            'role_id' => $this->adminRole->id,
            'is_active' => true,
        ]);
    }

    public function test_superadmin_can_create_employee_user_for_business_with_autogenerated_password(): void
    {
        $response = $this->actingAs($this->superadmin)
            ->post(route('superadmin.businesses.users.store', $this->business), [
                'name' => 'Marta Mesera',
                'email' => 'marta.mesera@puntostock.co',
                'role' => 'employee',
                'password' => '', // Dejar vacío para autogenerar
            ]);

        $response->assertRedirect(route('superadmin.businesses.users', $this->business));
        $response->assertSessionHas('temp_password');

        $tempPassword = session('temp_password');
        $this->assertNotEmpty($tempPassword);
        $this->assertGreaterThanOrEqual(16, strlen($tempPassword));

        $newUser = User::where('email', 'marta.mesera@puntostock.co')->first();
        $this->assertNotNull($newUser);
        $this->assertEquals('Marta Mesera', $newUser->name);
        $this->assertTrue((bool) $newUser->must_change_password);
        $this->assertFalse((bool) $newUser->is_superadmin);
        $this->assertTrue(Hash::check($tempPassword, $newUser->password));

        $this->assertDatabaseHas('business_user', [
            'business_id' => $this->business->id,
            'user_id' => $newUser->id,
            'role_id' => $this->employeeRole->id,
            'is_active' => true,
        ]);
    }

    public function test_email_must_be_globally_unique_in_users_table(): void
    {
        User::factory()->create([
            'email' => 'existente@puntostock.co',
        ]);

        $response = $this->actingAs($this->superadmin)
            ->from(route('superadmin.businesses.users.create', $this->business))
            ->post(route('superadmin.businesses.users.store', $this->business), [
                'name' => 'Duplicado User',
                'email' => 'existente@puntostock.co',
                'role' => 'employee',
            ]);

        $response->assertRedirect(route('superadmin.businesses.users.create', $this->business));
        $response->assertSessionHasErrors(['email']);
    }

    public function test_non_superadmin_cannot_access_collaborator_creation_routes(): void
    {
        $response = $this->actingAs($this->normalUser)
            ->get(route('superadmin.businesses.users.create', $this->business));

        $response->assertNotFound();

        $postResponse = $this->actingAs($this->normalUser)
            ->post(route('superadmin.businesses.users.store', $this->business), [
                'name' => 'Intruso',
                'email' => 'intruso@puntostock.co',
                'role' => 'employee',
            ]);

        $postResponse->assertNotFound();
    }
}
